const express=require("express")
const router=express.Router()
const authMiddleware=require("../middleware/auth.middleware")
const userController=require("../controllers/auth.controller")
router.post("/register",userController.register)
router.post("/login",userController.login)
router.get("/me",authMiddleware,userController.getMe)
router.put("/update-profile",authMiddleware,userController.updateProfile)
router.post("/logout",authMiddleware,userController.logout)
module.exports=router