const express=require("express")
const router=express.Router()
const authMiddleware=require("../middleware/auth.middleware")
const isOwner=require("../middleware/projectowner.middleware")
const projectController=require("../controllers/project.controller")    
router.post("/create",authMiddleware,projectController.createProject)
router.get("/",projectController.getProjects)
router.get("/search",projectController.searchProject)
router.put("/update/:id",authMiddleware,isOwner,projectController.updateProject)
router.delete("/delete/:id",authMiddleware,isOwner,projectController.deleteProject)
router.post("/request",authMiddleware,projectController.requestToJoinProject)
router.post("/:id/respond",authMiddleware,isOwner,projectController.respondJoin)
router.post("/invite/:id", authMiddleware, isOwner, projectController.inviteMember)
router.post("/respond-invite/:id", authMiddleware, projectController.respondToInvitation)
router.get("/my-projects",authMiddleware,projectController.getMyProjects)
router.post("/remove-member/:id", authMiddleware, isOwner, projectController.removeMember)
router.get("/:id",projectController.getProjectById)
module.exports=router   